rnaedit/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from web import views

urlpatterns = [
#    url(r'^admin/', include(admin.site.urls)),
    url(r"^overview/$", views.home),
    url(r"^search/$", views.search),
    url(r"^embed_table/$", views.embed_sites),
    url(r"^barcode/$", views.barcode),
    url(r"^mirna/$", views.mirna_search),
    url(r"^mirna_results/$", views.mirna),
    url(r"^mirna_sites/(?P<mirna>.+)/$", views.mirna_sites),
    url(r"^barcode/(?P<bar>.+)/$", views.barcode),
    url(r"^sample/(?P<cancer>.+)/$", views.sample),
    url(r"^help/$", views.help),
    url(r"^contact/$", views.contact),
    url(r"^editing_detail/$", views.editing_detail),
    url(r"^download_csv/$", views.download_csv),
    url(r"^mi_rna_detail/$", views.mi_rna_detail),
    url(r"^mirexp/(?P<site>.+)/(?P<mir>.+)/$", views.mirexp),
    url(r"^km/(?P<cancer>.+)/(?P<site>.+)/(?P<cut>.+)/$", views.km),
    url(r"^img/mirna/1/(?P<cancer>.+)/(?P<g>.+)/(?P<lt>.+)/$", views.mirnaimg1),
    url(r"^img/sites/1/(?P<cris>.+)/(?P<tar>.+)/(?P<rd>.+)/$", views.sitesimg1),
    url(r"^img/sites/2/(?P<cris>.+)/(?P<tar>.+)/(?P<rd>.+)/$", views.sitesimg2),
    url(r"^img/sites/3/(?P<cris>.+)/(?P<tar>.+)/(?P<rd>.+)/$", views.sitesimg3),
    url(r"^img/sites/4/(?P<cris>.+)/(?P<tar>.+)/(?P<rd>.+)/$", views.sitesimg4),
    url(r"^img/sites/5/(?P<cris>.+)/(?P<tar>.+)/(?P<rd>.+)/$", views.sitesimg5),
    url(r"^img/cancers/1/(?P<cancer>.+)/(?P<rd>.+)/$", views.cancersimg1),
    url(r"^img/cancers/2/(?P<cancer>.+)/(?P<rd>.+)/$", views.cancersimg2),
    url(r"^img/cancers/3/(?P<cancer>.+)/(?P<rd>.+)/(?P<lr>.+)/$", views.cancersimg3),
#    url(r"^addSample/$", views.addSample),
#    url(r"^updateSample/$", views.updateSample),
#    url(r"^addSite/$", views.addSite),
#    url(r"^updateSite/$", views.updateSite),
#    url(r"^addLevel/(?P<cancer>.+)/$", views.addLevel, name='addLevel'),
]

web/models.py
from django.db import models


class Sample(models.Model):
    sample_barcode = models.CharField(primary_key=True, max_length=50, default="")
    cancer_type = models.CharField(max_length=10, default="")
    is_tumor = models.BooleanField(default=True)
    stage_event_clinical_stage = models.CharField(max_length=15, default="")
    stage_event_pathologic_stage = models.CharField(max_length=15, default="")
    tnm_categories_pathologic_M = models.CharField(max_length=10, default="")
    tnm_categories_pathologic_N = models.CharField(max_length=10, default="")
    tnm_categories_pathologic_T = models.CharField(max_length=10, default="")
    age_at_initial_pathologic_diagnosis = models.IntegerField(null=True, default=None)
    days_to_birth = models.IntegerField(null=True, default=None)
    days_to_death = models.IntegerField(null=True, default=None)
    days_to_last_followup = models.CharField(max_length=10, default="")
    is_male = models.BooleanField(default=False)
    histological_type = models.CharField(max_length=100, default="")
    history_of_neoadjuvant_treatment = models.CharField(max_length=50, default="")
    other_dx = models.CharField(max_length=50, default="")
    person_neoplasm_cancer_status = models.CharField(max_length=10, default="")
    postoperative_rx_tx = models.NullBooleanField(default=None)
    radiation_therapy = models.NullBooleanField(default=None)
    tissue_prospective_collection_indicator = models.NullBooleanField(default=None)
    tissue_retrospective_collection_indicator = models.NullBooleanField(default=None)
    tumor_tissue_site = models.CharField(max_length=100, default="")
    vital_status = models.NullBooleanField(default=None)
    year_of_initial_pathologic_diagnosis = models.IntegerField(null=True, default=None)
    valid_site = models.IntegerField(null=True, default=None)

    def __str__(self):
        return self.sample_barcode


class Gtexsample(models.Model):
    scan = models.CharField(primary_key=True, max_length=14, default="")
    tissue = models.CharField(max_length=35, default="")


class Mirna(models.Model):
    name = models.CharField(max_length=30, primary_key=True)
    accession = models.CharField(max_length=40)
    seq = models.CharField(max_length=40, default='')
    p5 = models.DecimalField(max_digits=10, decimal_places=4)
    p50 = models.DecimalField(max_digits=10, decimal_places=4)
    p95 = models.DecimalField(max_digits=10, decimal_places=4)

    def __str__(self):
        return self.name


class Site(models.Model):
    key = models.CharField(max_length=100, primary_key=True)
    chromo = models.CharField(max_length=30)
    loc = models.PositiveIntegerField()
    hg19chr = models.CharField(max_length=30)
    hg19loc = models.PositiveIntegerField()
    hg19str = models.NullBooleanField()
    aa = models.PositiveIntegerField(default=0)
    gene = models.CharField(max_length=180)
    strand = models.NullBooleanField()
    region = models.CharField(max_length=25)
    location = models.CharField(max_length=20)
    repetitive = models.CharField(max_length=20)
    conserve = models.CharField(max_length=30)
    num_of_edited_samples = models.PositiveIntegerField(default=0)
    ref = models.CharField(max_length=1)
    ed = models.CharField(max_length=1)
    edit_percent = models.DecimalField(max_digits=5, decimal_places=2, null=True, default=0.0)
    gain = models.PositiveIntegerField(default=0)
    loss = models.PositiveIntegerField(default=0)
    snp_id = models.CharField(max_length=20, default=".")
    cosmic = models.CharField(max_length=15, default=".")
    exac = models.DecimalField(max_digits=8, decimal_places=8, null=True)
    gg = models.DecimalField(max_digits=8, decimal_places=8, null=True)
    intervar = models.CharField(max_length=20, default=".")
    clin = models.CharField(max_length=20, default=".")
    clin_sig = models.PositiveSmallIntegerField(default=0)
    clin_dbn = models.CharField(max_length=75)
    redi = models.NullBooleanField(default=False)
    hyper = models.NullBooleanField(default=False)
    gain_mir = models.ManyToManyField(Mirna, related_name='wild_sites')
    loss_mir = models.ManyToManyField(Mirna, related_name='edit_sites')
    def __str__(self):
        return self.key


class siteAnno(models.Model):
    site = models.OneToOneField(Site, on_delete=models.CASCADE, primary_key=True)
    tumor33 = models.DecimalField(max_digits=4, decimal_places=2, null=True)
    normal33 = models.DecimalField(max_digits=4, decimal_places=2, null=True)
    edint = models.PositiveIntegerField(default=0)
    edinn = models.PositiveIntegerField(default=0)
    radar = models.BooleanField(default=False)
    darned = models.BooleanField(default=False)
    has_cox = models.PositiveSmallIntegerField(default=0)



class rediLevel(models.Model):
    nas = models.PositiveIntegerField(default=0)
    ngs = models.PositiveIntegerField(default=0)
    level = models.DecimalField(max_digits=3, decimal_places=2, null=True)
    gcover = models.PositiveIntegerField(default=0)
    gfreq = models.DecimalField(max_digits=3, decimal_places=2, null=True)
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    sample = models.ForeignKey(Gtexsample, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.level)


class LevelLite(models.Model):
    level = models.DecimalField(max_digits=4, decimal_places=3, null=True)
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    sample = models.ForeignKey(Sample, on_delete=models.CASCADE)
    redi_A = models.PositiveIntegerField(default=0)
    redi_G = models.PositiveIntegerField(default=0)
    hyper_A = models.PositiveIntegerField(default=0)
    hyper_G = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.level)


class Level(models.Model):
    level = models.DecimalField(max_digits=4, decimal_places=3, null=True)
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    sample = models.ForeignKey(Sample, on_delete=models.CASCADE)
    redi_A = models.PositiveIntegerField(default=0)
    redi_G = models.PositiveIntegerField(default=0)
    hyper_A = models.PositiveIntegerField(default=0)
    hyper_G = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.level)


class Bind(models.Model):
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    mir = models.ForeignKey(Mirna, on_delete=models.CASCADE)
    chromo = models.CharField(max_length=30)
    utr = models.CharField(max_length=20)
    gstart = models.PositiveIntegerField()
    gend = models.PositiveIntegerField()
    qstart = models.PositiveIntegerField()
    qend = models.PositiveIntegerField()
    ustart = models.PositiveIntegerField()
    uend = models.PositiveIntegerField()
    energy = models.DecimalField(max_digits=7, decimal_places=3, null=True)
    score = models.DecimalField(max_digits=7, decimal_places=3, null=True)
    seed_type = models.CharField(max_length=10)
    mseq = models.CharField(max_length=40)
    binder = models.CharField(max_length=40)
    miseq = models.CharField(max_length=40)


class Miexp(models.Model):
    sample = models.ForeignKey(Sample, on_delete=models.CASCADE)
    mir = models.ForeignKey(Mirna, on_delete=models.CASCADE)
    exp = models.DecimalField(max_digits=10, decimal_places=3, null=True)


class Cancer(models.Model):
    abbr = models.CharField(max_length=4, primary_key=True)
    full = models.CharField(max_length=70, default="")
    tumorSample = models.PositiveSmallIntegerField(default=0)
    normalSample = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.abbr


class SiteEdinCancer(models.Model):  # in tumor tissues
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    cancer = models.ForeignKey(Cancer, on_delete=models.CASCADE)
    edin5 = models.PositiveIntegerField(default=0)
    p50 = models.DecimalField(max_digits=5, decimal_places=4)
    tumor = models.NullBooleanField(default=None)


class SiteEdinTN(models.Model):  # in tumor tissues
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    cancer = models.ForeignKey(Cancer, on_delete=models.CASCADE)
    edin5 = models.PositiveIntegerField(default=0)
    edin5p = models.PositiveIntegerField(default=0)
    p50 = models.DecimalField(max_digits=5, decimal_places=4)
    p50p = models.PositiveIntegerField(default=0)
    tumor = models.NullBooleanField(default=None)



class SiteEdin(models.Model):  # in tumor tissues
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    cancer = models.ForeignKey(Cancer, on_delete=models.CASCADE)
    edin = models.PositiveIntegerField(default=0)
    edin5 = models.PositiveIntegerField(default=0)
    p50 = models.DecimalField(max_digits=5, decimal_places=4)
    mean = models.DecimalField(max_digits=5, decimal_places=4)


class SiteEdinTumor(models.Model):  # in tumor tissues
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    cancer = models.ForeignKey(Cancer, on_delete=models.CASCADE)
    edin5 = models.PositiveIntegerField(default=0)
    p50 = models.DecimalField(max_digits=5, decimal_places=4)


class SiteEdinNormal(models.Model):  # in tumor tissues
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    cancer = models.ForeignKey(Cancer, on_delete=models.CASCADE)
    edin5 = models.PositiveIntegerField(default=0)
    p50 = models.DecimalField(max_digits=5, decimal_places=4)


class MiexpCancer(models.Model):  # in both tissues
    mirna = models.ForeignKey(Mirna, on_delete=models.CASCADE)
    cancer = models.ForeignKey(Cancer, on_delete=models.CASCADE)
    edin = models.PositiveIntegerField(default=0)
    p0 = models.DecimalField(max_digits=10, decimal_places=4)
    p25 = models.DecimalField(max_digits=10, decimal_places=4)
    p50 = models.DecimalField(max_digits=10, decimal_places=4)
    p75 = models.DecimalField(max_digits=10, decimal_places=4)
    p100 = models.DecimalField(max_digits=10, decimal_places=4)

templates/bar_result_table.html
{% extends 'base.html' %}
{% load static %}
{% block title %} REdiC: Cancer RNA Editing Database{% endblock %}
{% block headscript %}
<style type="text/css">
.ui.mywide.embed {
  padding-bottom: 40%;
}
.ui.levels.embed {
  padding-bottom: 0%;
}
</style>
{% endblock %}
{% block content %}
<!--小區塊，裡面放搜尋結果的heade，顯示使用者看他們是搜尋什麼東西-->
<div class="ui basic segment">
	<div class="ui center aligned container">
		{% if sample_module.sample_barcode %}
			<h1 class="ui  header">Editing events of&nbsp;:</h1>
			<h2 class="ui  header">{{ sample_module.sample_barcode }} ({{sample_module.cancer_type}})</h2>  
			
		{% else %}
			<h2 class="ui red header">Sample barcode not found! Please try again</h2>
		{% endif %}
	</div>
</div>

<div class="ui basic segment">
	<div class="ui grid">
	  <div class="three wide column"></div>
	  <div class="ten wide column">
	  	<h2 class="ui center aligned header" onclick="p1pop()">Top 10 Edited Sites</h2>
	  	<div class="ui basic segment">
	  	<div class="ui active dimmer" id="p1loader">
	      <div class="ui massive text loader">Loading</div>
	    </div>
	  	<div class="ui mywide embed" data-url="/img/sites/6/{{ sample_module.sample_barcode }}/p1/{{ rd }}/">
		</div>
		</div>
	  </div>
	  <div class="three wide column"></div>
	</div>
<div class="ui levels embed" id="levels_embed"></div>
</div>
<script type="text/javascript">
$('.ui.mywide.embed').embed();
var url = "/embed_level/{{ sample_module.sample_barcode }}/";
$('.ui.levels.embed').embed({
  url : url
});
function alterHeight(h, id){
	$('#' + id).height(h);
}
$('#pointp1').prev('div').children().children().attr("scrolling", "yes");
$('#pointp2').prev('div').children().children().attr("scrolling", "yes");
$('.ui.accordion').accordion();
$('.menu .item').tab();
function p1pop() {
	$(function(){
		$(".fullscreen.p1big").modal('show');
	});
}
function p2pop() {
	$(function(){
		$(".fullscreen.p2big").modal('show');
	});
}
function p1load(target_id, img_src) {
    document.getElementById(target_id + "loader").setAttribute("class", "ui disabled loader");
	var DOM_img = document.createElement("img");
	DOM_img.src = img_src;
	//document.getElementById(target_id + 'img').appendChild(DOM_img);
}
</script>
{% endblock %}

templates/mirna_by_site.html
{% extends 'base.html' %}
{% load static %}
{% block title %}REdiC: Cancer RNA Editing Database{% endblock %}
{% block headscript %}
<!-- Heatmap starts -->
<script src="https://d3js.org/colorbrewer.v1.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static "css/heatmap.css" %}">
<script src="{% static "js/heatmap.js" %}"></script>
<!-- Heatmap ends -->
<script src="http://d3js.org/d3.v3.js"></script>
<style type="text/css">
.Consolas{
font-family: Consolas;
}
</style>
{% load mathfilters %}
{% endblock %}
{% block content %}
<div class="ui container" id="page">
  <div class="ui center aligned container">
    <h1 class="ui header">filtered miRNAs</h1>
    {% for key, value in cri.items %}
    <div class="ui label">
      {{key}}
      <div class="detail">{{value}}</div>
    </div>
    {% endfor %}
  </div>
  <div class="ui horizontal list">
    <div class="item">
      <div class="ui menu">
        <div class="ui simple dropdown item">
          Show {{ datas_per_page }} rows
          <i class="dropdown icon"></i>
          <div class="menu">
            {% with "10 25 50 100" as list %}
              {% for i in list.split %}
                {% if i == "datas_per_page" %}
                  <a class="disabled item">{{ i }} rows</a>
                {% else %}
                  <a class="item" href="?{{ page_record }}&datas_per_page={{ i }}">{{ i }} rows</a>
                {% endif %}
              {% endfor %}
            {% endwith %}
          </div>
        </div>
      </div>
    </div>
  </div>

  <table class="ui blue striped celled accordion table">
    <!--此放table的header，header放的為搜尋結果的資料分類-->
    <thead>
      <tr>
        <th class="center aligned">
          <a href="?{{ search_record }}&click_sort=mirna">
            miRNA
            {% if current_sort == "mirna" %}
              <i class="caret {{ sorted_direction }} icon"></i>
            {% endif %}
          </a>
        </th>
        <th class="center aligned">
          <a href="?{{ search_record }}&click_sort=gain">
            #sites cause gain / loss
            {% if current_sort == "gain" %}
              <i class="caret {{ sorted_direction }} icon"></i>
            {% endif %}
          </a>
        </th>
        <th class="center aligned">
          <a href="?{{ search_record }}&click_sort=p50t">
            exp in {{ cancer }}
            {% if current_sort == "p50t" %}
              <i class="caret {{ sorted_direction }} icon"></i>
            {% endif %}
          </a>
        </th>
        <!--
        <th class="center aligned">
          <a href="?{{ search_record }}&click_sort=p50n">
            exp in {{ cancer }} (normal)
            {% if current_sort == "p50n" %}
              <i class="caret {{ sorted_direction }} icon"></i>
            {% endif %}
          </a>
        </th>
        -->
      </tr>
    </thead>
    <!--此放搜尋結果的資料，依header排列的資料種類順序放置對應的資料種類-->
    <tbody>
      {% for mirna in mirnas %}
      <tr class="title">
          <td class="center aligned"><a href="http://www.mirbase.org/cgi-bin/mirna_entry.pl?acc={{ mirna.accession }}" target="_blank">{{ mirna }}</a></td>
          <td class="center aligned"><a class="medium ui label" href="/mirna_sites/{{ mirna }}/">{{ mirna.wild_sites.all|length }} / {{ mirna.edit_sites.all|length }}</a></td>
          <td class="center aligned">{{ mirna.p50 }}</td>
      </tr>
      <div class="content">
        <tr>
          <td colspan="5" class="transition hidden">
            <div id="chart_{{ mirna }}" class="ui fluid center aligned container"></div>
            <script type="text/javascript">
            var data = [];
            {% for exp in mirna.miexpcancer_set.all %}
              {% if exp.is_tumor == 1 %}
                var block = {'day': 2, 'hour': cam2num['{{ exp.cancer }}'], 'value': {{ exp.p50 }}};
              {% else %}
                var block = {'day': 1, 'hour': cam2num['{{ exp.cancer }}'], 'value': {{ exp.p50 }}};
              {% endif %}
              data.push(block);
            {% endfor %}
            heatmapChart(data, 
              "chart_{{ mirna }}", 
              $('#page').width() * 0.95, 
              $('#page').width() * 0.12);
            </script>
          </td>
        </tr>
      </div>  
      {% empty %}
      <tr class="center aligned"><td colspan="11"><h2 class="ui orange header">No results found</h2></td></tr>      
      {% endfor %}

    </tbody>
    <!--放置搜尋資料的最後一列，這邊我們一樣放的是跟header一樣的東西，不同的事此列有設置按鈕可以對資料做篩選-->
    <tfoot>
    <tr>
      <th class="center aligned">
        <a href="?{{ search_record }}&click_sort=mirna">
          miRNA
          {% if current_sort == "mirna" %}
            <i class="caret {{ sorted_direction }} icon"></i>
          {% endif %}
        </a>
      </th>
      <th class="center aligned">
        <a href="?{{ search_record }}&click_sort=gain">
          #sites cause gain / loss
          {% if current_sort == "gain" %}
            <i class="caret {{ sorted_direction }} icon"></i>
          {% endif %}
        </a>
      </th>
      <th class="center aligned">
        <a href="?{{ search_record }}&click_sort=p50t">
          exp in {{ cancer }}
          {% if current_sort == "p50t" %}
            <i class="caret {{ sorted_direction }} icon"></i>
          {% endif %}
        </a>
      </th>
      <!--
      <th class="center aligned">
        <a href="?{{ search_record }}&click_sort=p50n">
          exp in {{ cancer }} (normal)
          {% if current_sort == "p50n" %}
            <i class="caret {{ sorted_direction }} icon"></i>
          {% endif %}
        </a>
      </th>
      -->
    </tr>
    </tfoot>
  </table>

  <!--如果搜尋的資料超過一頁的話執行以下程式碼-->
  {% if mirnas.has_other_pages %}
  <div class="ui horizontal list">
    <!--此item放可點選的分頁-->
      <div class="item">
        <div class="ui pagination menu">
          <!--如果所在的分頁有上一頁的話執行以下指令-->
          {% if mirnas.has_previous %}
            <!--使上一頁的按鈕可供點選，且導向上一頁-->
          <a class="item" href="?page={{ mirnas.number|add:-1 }}&{{ search_record }}" name="page">
            <<
          </a>
        {% else %}
          <!--若無上一頁則停止上一頁這個按鈕的功能-->
          <div class="disabled item">
            <<
          </div>
        {% endif %} 
        <!--如果所在的頁碼<=5的話則執行以下指令-->
        {% if mirnas.number <= 5 %}
          <!--如果總頁數少於等於7的話執行以下指令，因為我這邊設計頁碼的格子為7格-->
          {% if mirnas.paginator.num_pages <= 7 %}
            <!--對所有頁碼做迴圈for ..in-->
            {% for i in mirnas.paginator.page_range %}
              <!--如果此頁碼等於目前所在的頁碼的話，使這個頁碼按鈕有被向下按的感覺-->
              {% if i == mirnas.number %}
                <a class="active item" href="?page={{ i }}&{{ search_record }}" name="page">{{ i }}</a>
              <!--若此頁碼非所在頁面的話，則讓按鈕為沒被按的樣子-->
              {% else %}
                <a class="item" href="?page={{ i }}&{{ search_record }}" name="page">{{ i }}</a>
              {% endif %}
            {% endfor %}
          <!--如果總頁數大於7的話，執行以下指令，因為設計頁碼格子最多為7所以總頁數超過7的話必有某些個子要用來設計為...符號-->
          {% else %}
            <!--對頁碼做迴圈-->
            {% for i in mirnas.paginator.page_range %}
              <!--如果此頁碼等於目前所在的頁碼的話，使這個頁碼按鈕有被向下按的感覺-->
              {% if i == mirnas.number %}
                <a class="active item" href="?page={{ i }}&{{ search_record }}" name="page">{{ i }}</a>
              <!--將小於等於5的頁碼都顯示出來，並且讓按鈕為沒被按的樣子-->
              {% elif i <= 5 %}
                <a class="item" href="?page={{ i }}&{{ search_record }}" name="page">{{ i }}</a>
              {% endif %}
            {% endfor %}
            <!--此為省略中間頁碼的按鈕，沒有功能-->
            <div class="disabled item">...</div>
            <!--在省略中間頁碼的按鈕後加上最後一夜的頁碼的按鈕，使使用者方便找到最後一筆資料-->
            <a class="item" href="?page={{ mirnas.paginator.num_pages }}&{{ search_record }}" name="page">{{ mirnas.paginator.num_pages }}</a>
          {% endif %}
        <!--如果所在頁碼在離最後頁碼四頁以內的話，執行以下指令-->
        {% elif mirnas.number > mirnas.paginator.num_pages|add:-4 %}
          <!--如果所在頁碼在離最後頁碼四頁以內的話，還是要顯示第一頁頁碼讓使用者方便瀏覽資料-->
          <a class="item" href="?page=1&{{ search_record }}" name="page">1</a>
          <!--除了第一頁以外，中間的頁碼全部用...替代-->
          <div class="disabled item">...</div>
          <!--對後四頁做迴圈，如果頁碼為所在頁面的話則給予按鈕被向下壓的感覺-->
          {% for i in mirnas.paginator.page_range %}
            {% if i == mirnas.number %}
              <a class="active item" href="?page={{ i }}&{{ search_record }}" name="page">{{ i }}</a>
            {% elif i >= mirnas.paginator.num_pages|add:-4 %}
              <a class="item" href="?page={{ i }}&{{ search_record }}" name="page">{{ i }}</a>
            {% endif %}
          {% endfor %}
        <!--如果所在頁碼不在前五頁或後四頁的話，執行以下指令-->
        {% else %}
          <!--對所有頁碼做迴圈，如果頁碼為所在頁面的話則給予按鈕被向下壓的感覺-->
          {% for i in mirnas.paginator.page_range %}
            <!--所在頁碼在中間，但第一頁和省略頁還是要顯示出來(第一、二格）-->
            {% if i == 1 %}
              <a class="item" href="?page={{ i }}&{{ search_record }}" name="page">{{ i }}</a>
              <div class="disabled item">...</div>
            <!--如果此頁碼為所在頁碼，則給予按鈕被向下壓的感覺(第四格）-->
            {% elif mirnas.number == i %}
              <a class="active item" href="?page={{ i }}&{{ search_record }}" name="page">{{ i }}</a>
            <!--如果此頁碼為所在頁碼的前後一頁的話，則讓按鈕顯示(第三、五格）-->
            {% elif i < mirnas.number|add:2 and i > mirnas.number|add:-2 %}
              <a class="item" href="?page={{ i }}&{{ search_record }}" name="page">{{ i }}</a>
            <!--所在頁碼在中間，但最後一頁和省略頁還是要顯示出來(第六、七格）-->
            {% elif i == mirnas.paginator.num_pages %}
              <div class="disabled item">...</div>
              <a class="item" href="?page={{ i }}&{{ search_record }}" name="page">{{ i }}</a>
            {% endif %}
          {% endfor %}
        {% endif %}
        <!--如果所在的分頁有下一頁的話執行以下指令-->
        {% if mirnas.has_next %}
          <!--使下一頁的按鈕可供點選，且導向下一頁-->
          <a class="item" href="?page={{ mirnas.number|add:1 }}&{{ search_record }}" name="page"></a>
        {% else %}
          <!--若無下一頁則停止下一頁這個按鈕的功能-->
          <div class="blue disabled item"></div>
        {% endif %}
      </div>
    </div>

    <!--此item放可供搜尋的搜尋欄-->
    <div class="item">
      <form class="ui floated form" action="" method="get">
        <!--用隱藏的欄位將此搜尋頁面的搜尋條件儲存起來，使用者輸入頁碼後一樣用此搜尋條件去找資料庫，只是最後回傳不同頁碼的結果-->
        {% for key, value in search_request_dict.items %}
          <input type="hidden" name="{{key}}" value="{{value}}">
        {% endfor %}
        <!--創建一個搜尋欄-->
        <div class="ui  floated action input">
          <input type="text" id="page_input" style="ime-mode:disabled" placeholder="Page to..." name="page">
          <!--使搜尋欄只能輸入數字，且數字不能大於最大頁碼-->
          <script type="text/javascript">
            var text = document.getElementById("page_input");
            text.onkeyup = function(){
              this.value=this.value.replace(/\D/g,'');
              if(text.value>{{ mirnas.paginator.num_pages }}){
                  text.value = {{ mirnas.paginator.num_pages }};
                }
            }
          </script>
          <button class="ui button" type="submit">Go</button>
        </div>
      </form>
    </div>
  {% endif %}
  </div>
</div>
<script type="text/javascript">
$('.ui.accordion').accordion();
</script>
{% endblock %}